{
'inculdes': {}, 
'bd_ver': 11, 
'toolchain': 'gnu', 
'name': 'baremetal_arc_feature_cache',
'cur_core': 'arcem4', 
'c_defines': [u'BOARD_EMSK', u'BOARD_SPI_FREQ=800000', u'BOARD_WIFI_SEL=0', u'CPU_ARC', u'CURRENT_CORE=arcem4', u'EMBARC_TCF_GENERATED', u'EMBARC_USE_BOARD_MAIN', u'HW_VERSION=11', u'LIB_CLIB', u'MID_COMMON', u'PLATFORM_EMBARC', u'TOOLCHAIN=ARC_GNU', u'_HAVE_LIBGLOSS_', u'_HEAPSIZE=8192', u'_STACKSIZE=8192', u'__GNU__'], 
'sources': ['arc', 'board', 'device', 'inc', 'middleware', 'library', 'options', 'os'], 
'appl': 'baremetal_arc_feature_cache', 
'board': 'emsk', 
'path_list': ['example', 'example/baremetal', 'example/baremetal/arc_feature', 'example/baremetal/arc_feature/cache'], 
'path': 'example/baremetal/arc_feature/cache', 
'workspace_depth': 3, 
'c_includes': [u'baremetal_arc_feature_cache\\example\\baremetal\\arc_feature\\cache', u'baremetal_arc_feature_cache\\arc', u'baremetal_arc_feature_cache\\board', u'baremetal_arc_feature_cache\\board\\emsk\\configs\\11', u'baremetal_arc_feature_cache\\device\\designware\\gpio', u'baremetal_arc_feature_cache\\device\\designware\\iic', u'baremetal_arc_feature_cache\\device\\designware\\spi', u'baremetal_arc_feature_cache\\device\\designware\\uart', u'baremetal_arc_feature_cache\\device\\device_hal\\inc', u'baremetal_arc_feature_cache\\device\\microchip\\mrf24g', u'baremetal_arc_feature_cache\\device\\rtthread\\rw009', u'baremetal_arc_feature_cache\\inc', u'baremetal_arc_feature_cache\\inc\\arc', u'baremetal_arc_feature_cache\\library\\clib', u'baremetal_arc_feature_cache\\middleware\\common', u'baremetal_arc_feature_cache\\middleware\\common\\ringbuffer', u'baremetal_arc_feature_cache\\middleware\\common\\xprintf', u'baremetal_arc_feature_cache\\example\\baremetal\\arc_feature\\cache\\obj_emsk_11\\gnu_arcem4\\embARC_generated'], 
'root': 'C:\\Users\\jingru\\Documents\\embarc_tool\\embARC_2017.03-RC2\\embARC', 
'outdir': '${ProjDirPath}'}