## embARC application makefile template ##
### You can copy this file to your application folder
### and rename it to makefile.
##

# Application name
APPL ?= {{APPL}}

# Optimization Level
# Please Refer to toolchain_xxx.mk for this option
OLEVEL ?= {{olevel}}

##
# Current Board And Core
##
BOARD ?= {{BOARD}}
BD_VER ?= {{BD_VER}}
CUR_CORE ?= {{CUR_CORE}}

##
# select debugging jtag
##
JTAG ?= usb

##
# Set toolchain
##
TOOLCHAIN ?= {{TOOLCHAIN}}

##
# Uncomment following options
# if you want to set your own heap and stack size
# Default settings see options.mk
##
#HEAPSZ ?= 8192
#STACKSZ ?= 8192

##
# Uncomment following options
# if you want to add your own library into link process
# For example:
# If you want link math lib for gnu toolchain,
# you need to set the option to -lm
##
#APPL_LIBS ?=
OS_SEL ?= {{os}}
LIB_SEL ?= {{lib}}
#
# root dir of embARC
#
EMBARC_ROOT = {{EMBARC_OSP_ROOT}}

MID_SEL = {{middleware}} #common

# application source dirs
APPL_CSRC_DIR = {{csrc}} 
APPL_ASMSRC_DIR = {{asmsrc}} 

# application include dirs
APPL_INC_DIR = {{include}} 

# application defines
APPL_DEFINES = {{defines}} 

# include current project makefile
COMMON_COMPILE_PREREQUISITES += makefile

### Options above must be added before include options.mk ###
# include key embARC build system makefile
override EMBARC_ROOT := $(strip $(subst \,/,$(EMBARC_ROOT)))
include $(EMBARC_ROOT)/options/options.mk
